-- -- Disconnect all users connected to the database
-- SELECT pg_terminate_backend(pg_stat_activity.pid)
-- FROM pg_stat_activity
-- WHERE pg_stat_activity.datname = 'note'
--   AND pid <> pg_backend_pid();
--
-- -- Now drop the database
-- DROP DATABASE note;
--
--
-- -- Drop and create the note database
-- DROP DATABASE IF EXISTS note;
-- CREATE DATABASE note;