AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda for Go microservice (without API Gateway)

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment
  ProjectName:
    Type: String
    Default: go-microservice
    Description: Name of the project/microservice

Resources:
  GolangStarterTemplateFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}"
      Runtime: provided.al2023
      Handler: bootstrap
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: YOUR_DEPLOYMENT_BUCKET_NAME
        S3Key: YOUR_ZIP_FILE_PATH
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          LOG_LEVEL: info
      Tags:
        - Key: Service
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  LambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt GoLambdaFunction.Arn
  LambdaRegion:
    Description: "Region where the Lambda is deployed"
    Value: !Ref AWS::Region